prod:
  children:
    odoo_prod:
      hosts:
        odoo_server_prod:
    ic_webapp_pgadmin_prod:
      hosts:
        ic_webapp_pgadmin_server_prod
staging:
  children:
    odoo_staging:
      hosts:
        odoo_server_staging:
    ic_webapp_pgadmin_staging:
      hosts:
        ic_webapp_pgadmin_server_staging      
