apiVersion: v1
kind: ConfigMap
metadata:
  name: ic-webapp-config
  labels:
    app: ic-webapp
  namespace: ic-group-intranet
data:
  ODOO_URL: http://192.168.56.6:30069
  PGADMIN_URL: http://192.168.56.6:30050
