apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-persistent-storage
  labels:
    app: odoo
    type: local
  namespace: ic-group-intranet
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ic_data/data-odoo-pv"     
