---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
  namespace: ic-group-intranet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin 
    spec:
      containers:
        - image: dpage/pgadmin4
          name: pgadmin
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "pgadmin@ic-group.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-pass
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - containerPort: 80
              name: pgadmin
          volumeMounts:
            - name: pgadmin-persistent-storage
              mountPath: /var/lib/pgadmin
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: pgadmin-persistent-storage
          persistentVolumeClaim:
            claimName: pgadmin-persistent-storage
        - name: pgadmin-config
          configMap:
            name: pgadmin-config

