apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-persistent-storage
  labels:
    app: pgadmin
  namespace: ic-group-intranet
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
