apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-storage
  labels:
    app: postgres
    type: local
  namespace: ic-group-intranet
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ic_data/data-postgres-pv"
