apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-storage
  labels:
    app: postgres
  namespace: ic-group-intranet
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
