apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
  namespace: ic-group-intranet
spec:
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 80
    nodePort: 30050
  selector:
    app: pgadmin
  type: NodePort
