apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app: odoo
  namespace: ic-group-intranet
spec:
  ports:
  - protocol: TCP
    port: 8069
    targetPort: 8069
    nodePort: 30069
  selector:
    app: odoo
  type: NodePort
