---
- name: Download pip script
  get_url:
      url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
      dest: /tmp/get-pip.py
- name: Install python-pip
  command: python3 /tmp/get-pip.py
  ignore_errors: yes

- name: Install docker python
  pip:
    name: docker-py
    executable: /usr/local/bin/pip3
- name: dowload docker script install
  command: curl -fsSL https://get.docker.com -o install-docker.sh

- name: install docker
  command: sudo sh install-docker.sh
  become: true
  notify: start_service_docker

- name: Force notified handlers to run at this point
  meta: flush_handlers

- name: Add user to docker group
  user:
    name: "{{system_user}}"
    groups: docker
    append: true

- name: Reset ssh connection to allow user changes to affect ansible user
  meta:
    reset_connection

- name: Force notified handlers to run at this point
  meta: flush_handlers
